import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { CBody, CFooter, CHeader, CLayout } from "@/containers/layouts";
import { ReactQueryClientProvider } from "@/hooks/useReactQuery";
import ReduxProvider from "@/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <ReduxProvider>
        <html lang="ko" suppressHydrationWarning>
          <head>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
          </head>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <CLayout>{children}</CLayout>
          </body>
        </html>
      </ReduxProvider>
    </ReactQueryClientProvider>
  );
}
